deployments:
  MyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  xMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true
